#!/usr/bin/env python3
"""Send the morning brief email via Gmail SMTP."""

import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from dotenv import load_dotenv

# Load .env from the script's directory
load_dotenv(Path(__file__).parent / ".env")

GMAIL_ADDRESS = os.environ["GMAIL_ADDRESS"]
GMAIL_APP_PASSWORD = os.environ["GMAIL_APP_PASSWORD"]


def send_brief(subject: str, html_body: str):
    msg = MIMEMultipart("alternative")
    msg["From"] = f"Research Agent <{GMAIL_ADDRESS}>"
    msg["To"] = GMAIL_ADDRESS
    msg["Subject"] = subject

    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_ADDRESS, GMAIL_ADDRESS, msg.as_string())

    print(f"Email sent: {subject}")


if __name__ == "__main__":
    # When run directly, send the current morning-brief.md as email
    import sys
    import re
    from datetime import datetime

    brief_path = Path(__file__).parent / ".research" / "morning-brief.md"
    if not brief_path.exists():
        print("No morning-brief.md found")
        sys.exit(1)

    content = brief_path.read_text()

    # Extract topic from the brief
    topic_match = re.search(r"\*\*Topic:\*\*\s*(.+)", content)
    topic = topic_match.group(1) if topic_match else "Daily Research"

    today = datetime.now().strftime("%a, %B %-d")
    subject = f"\u2600\ufe0f Morning Brief \u2014 {today}: {topic}"

    # Convert markdown to basic HTML
    html = content
    # Bold
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    # Links
    html = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', html)
    # Headers
    html = re.sub(r"^## (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^# (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
    # List items
    html = re.sub(r"^- (.+)$", r"<li>\1</li>", html, flags=re.MULTILINE)
    html = re.sub(r"^(\d+)\. (.+)$", r"<li>\2</li>", html, flags=re.MULTILINE)
    # Tables (basic)
    html = re.sub(r"\|---.*\|", "", html)
    html = re.sub(
        r"^\| (.+) \|$",
        lambda m: "<tr>"
        + "".join(f"<td style='padding:8px; border:1px solid #ddd;'>{c.strip()}</td>" for c in m.group(1).split("|"))
        + "</tr>",
        html,
        flags=re.MULTILINE,
    )
    # Line breaks
    html = html.replace("\n", "<br>\n")

    html = f"""<html><body style="font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif; max-width: 600px; margin: 0 auto; color: #1a1a1a;">
{html}
<hr style="border: none; border-top: 1px solid #e0e0e0;">
<p style="color: #999; font-size: 12px;">Generated by your Strategic Research Agent</p>
</body></html>"""

    send_brief(subject, html)
